[package]
name = "mockall-issues"
version = "0.1.0"
authors = ["Ryan Stout <ryan.stout@dfinity.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
